---
##title: "Summer"
##author: "Brian S Yandell"
##date: "September 21, 2015"
output: html_document
---

**Summer Data Science Practicum**  

**Course Content:**
In an expanded Summer 3-credit version, students will work to get the attention of corporate leaders unfamiliar with data science. This starts with an “elevator speech” to gain access to a broader venue for presentation. Students will be able to follow up with immediate questions and with longer term commitment on project needs as they develop. This Summer version meets 3 hours per day, for days per week, for 4 weeks in Summer Session.

**Projects:** Go from initial, likely vague, description of a large data project to a well-crafted, accessible report, complete with graphics, interpretation and justification for choices. Students will be able to

* query project leader(s) about objectives
* articulate a plan of action
* communicate results clearly and succinctly

**Learning Objectives:** After completing this course, a student should be able to:

1. Organize projects into manageable steps
2. Present and argue merits of data analysis using language and visuals accessible to a broad audience
3. Develop realistic budget of time and resources for a partially formed data project

**Weekly Schedule:**
Students will work in teams. Each week will concern a different complex data project. In the case of a very complex big data project for the entire course, each week will focus on different aspect of the project. Meetings will include when possible visits by collaborators knowledgeable with the problem.
In each week, a team of students are expected to develop a plan during the first day, refine plan and share with each other initial graphics and results on second day, and finalize approach and plan for presentation on third day. Fourth day will be formal presentation of report, both written and oral, with critical feedback by peers, instructor and (when possible) collaborators. Fourth day will also involve recap of key points learned by each team member.